### ISSUE TITLE
能问下服务端用什么来做识别吗

### ISSUE THREAD

**Issue by UC10D** [byhieg/text-recognizer#2]
能问下服务端用什么来做识别吗

**Comment by byhieg** [comment]
服务端用Java来提供API,核心识别部分用tesseract。
服务端接受一个图片的文件，将文件传给tesseract程序，tesseract会将结果保存成文件。服务端读取结果文件的内容，发送给Android端。
关于tesseract的使用，可以参考[tesseract的例子](http://www.52itstyle.com/thread-4803-1-1.html)

**Comment by UC10D** [comment]
谢啦
